# Generated by Django 5.0.6 on 2024-06-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_product_attribute_delete_productattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attribute',
            field=models.ManyToManyField(blank=True, null=True, related_name='attributes', to='blog.attribute'),
        ),
    ]
