# Generated by Django 5.0.6 on 2024-06-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_product_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attribute',
            field=models.ManyToManyField(blank=True, related_name='attributes', to='blog.attribute'),
        ),
    ]
